integrate flatpak-setup in to package-config

diff --git a/quiver/package-config/flatpak b/quiver/package-config/flatpak
--- a/quiver/package-config/flatpak
+++ b/quiver/package-config/flatpak
@@ -1,26 +1,73 @@
 #!/bin/bash
-# shellcheck disable=SC2154,SC2002
+# shellcheck disable=SC2154,SC2002,SC2164,SC2086
 
-echo -e "Creating flatpak-setup desktop entry"
+echo -e "Creating flatpak-installer desktop entry"
 
 mkdir -p /home/"$user"/.config/autostart/
 chown "$user":"$user" /home/"$user"/.config/autostart/
 chmod 755 /home/"$user"/.config/autostart/
 
-cat <<END >>/home/"$user"/.config/autostart/flatpak-setup.desktop
+cat <<END >>/home/"$user"/.config/autostart/flatpak-installer.desktop
 [Desktop Entry]
-Exec=konsole -e /usr/bin/flatpak-setup
+Exec=konsole -e /usr/bin/flatpak-installer
 Icon=/usr/share/pixmaps/archlinux-logo.png
 StartupNotify=true
 Type=Application
 END
-chown "$user":"$user" /home/"$user"/.config/autostart/flatpak-setup.desktop
+chown "$user":"$user" /home/"$user"/.config/autostart/flatpak-installer.desktop
 
 echo -e "Setting up Flatpak install script"
 
-cat /Archer-main/quiver/scripts/flatpak-setup >/usr/bin/flatpak-setup
-chmod a+x /usr/bin/flatpak-setup
+flatpak_install_script() {
+#!/bin/bash
+user="UNIX_USER"
+packages="PACKAGE_LIST"
+
+clear
+echo -e "
+-------------------------------------------------------------------------
+$(tput setaf 4)
+             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
+            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
+            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
+            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
+            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
+            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
+$(tput sgr0)
+-------------------------------------------------------------------------
+                         Flatpak install script
+-------------------------------------------------------------------------"
+
+while ! ping -q -c 1 -W 1 archlinux.org > /dev/null 2>&1; do
+    echo "Waiting for internet connection..."
+	sleep 10
+done
+
+while true; do
+	flatpak install flathub -y --noninteractive $packages && break
+    echo "$(tput setaf 9)Package installation failed. Retrying...$(tput sgr0)"
+done
+
+echo -e "Fix game controller remote access pop up spam in KDE Plasma"
+flatpak permission-set kde-authorized remote-desktop "" yes
+
+# Setup flatpaks
+if [[ $(flatpak list) == *"com.flatpak.package.name"* ]]; then
+    # Example code to configure flatpaks
+    echo
+fi
+
+echo -e "-------------------------------------------------------------------------"
+read -r -t 5 -p "Rebooting in 5 seconds..."
+
+rm -f /home/$user/.config/autostart/flatpak-installer.desktop
+rm -f ${BASH_SOURCE[0]}
+reboot
+}
+
+awk '/^flatpak_install_script\(\) \{$/ { found=1; next } found && /^}$/ { exit } found { print }' "$0" > /usr/bin/flatpak-installer
+chmod a+x /usr/bin/flatpak-installer
 
 packages=$(sed -n '/# FLATPAK/{:a;n;/# FLATPAK/b;p;ba}' "/Archer-main/quiver/${install_type}_packages.txt" | tr '\n' ' ')
+sed -i "s/UNIX_USER/$user/g; s/PACKAGE_LIST/$packages/g" /usr/bin/flatpak-installer
 
-sed -i "s/UNIX_USER/$user/g; s/PACKAGE_LIST/$packages/g" /usr/bin/flatpak-setup
